WIP: Implement stress generator business logic
RHEAGROUP/CDP4-Server-Administration-Tool pull request #80
Opened 2020-11-13 13:56 UTC by adrianchivu

### Prerequisites

- [X] I have written a descriptive pull-request title
- [X] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-Server-Administration-Tool/pulls) open
- [X] I have verified that I am following the CDP4-Server-Administration-Tool [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-Server-Administration-Tool/master/.github/CONTRIBUTING.md)
- [X] I have provided test coverage for my change (where applicable)

### Description

2020-11-17 09:07 UTC, samatrhea requested changes

2020-11-17 09:07 UTC, samatrhea commented on Modules/StressGenerator/Utils/ElementDefinitionGenerator.cs
> +            var elementDefinition = new ElementDefinition(Guid.NewGuid(), session.Assembler.Cache,
when creating new Things to send to the server to get created it is not necessary to specify the cache and URI, see docs here https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/wiki/Transactions-and-Operations that would simplify this also not need the ISession as parameter for this method call

2020-11-17 09:07 UTC, samatrhea commented on Modules/StressGenerator/Utils/ParameterGenerator.cs
> +        public static Parameter Create(ISession session, ParameterType paramType,
can you make `paramType` be `parameterType`, makes it explicit, same comment for other parameters

2020-11-19 14:37 UTC, adrianchivu commented on Modules/StressGenerator/ViewModels/StressGeneratorViewModel.cs
> +                {DataSource.CDP4, "CDP4 WebServices"},
We shouldn't support here DataSource.JSON.

2020-11-19 14:51 UTC, adrianchivu commented on Modules/StressGenerator/Utils/ElementDefinitionGenerator.cs
> +            var elementDefinition = new ElementDefinition(Guid.NewGuid(), session.Assembler.Cache,
In the current element definition creation flow(for stresser) if I don't specify the parameters I will receive the next response from the server:
The CDP4 Services replied with code Forbidden: Forbidden: "exception:Item \u0027ElementDefinition\u0027 with Iid: \u002700000000-0000-0000-0000-000000000000\u0027 already exists"

2020-11-19 14:51 UTC, adrianchivu commented on Modules/StressGenerator/Utils/ParameterGenerator.cs
> +        public static Parameter Create(ISession session, ParameterType paramType,
Done.

2020-11-19 14:55 UTC, alexatrhea commented on Modules/StressGenerator/Utils/ElementDefinitionGenerator.cs
> +            var elementDefinition = new ElementDefinition(Guid.NewGuid(), session.Assembler.Cache,
You need the NewGuid(), but not the rest (they can be null)

2020-11-19 15:16 UTC, adrianchivu commented on Modules/StressGenerator/Utils/ElementDefinitionGenerator.cs
> +            var elementDefinition = new ElementDefinition(Guid.NewGuid(), session.Assembler.Cache,
k. Got it.

2020-11-19 16:03 UTC, alexatrhea requested changes
Some missing docs, no need to rereview from my side once fixed

2020-11-19 16:03 UTC, alexatrhea commented on Modules/StressGenerator/Utils/ParameterGenerator.cs
> +        /// <returns></returns>
missing doc

2020-11-19 16:03 UTC, alexatrhea commented on Modules/StressGenerator/Utils/StressGeneratorManager.cs
> +        /// <returns></returns>
missing doc

2020-11-19 16:03 UTC, alexatrhea commented on Modules/StressGenerator/Utils/StressGeneratorManager.cs
> +        /// <returns></returns>
missing doc

2020-11-19 16:03 UTC, alexatrhea commented on Modules/StressGenerator/Utils/StressGeneratorManager.cs
> +        /// <returns></returns>
missing doc

2020-11-19 16:03 UTC, alexatrhea commented on Modules/StressGenerator/Utils/StressGeneratorManager.cs
> +        /// <returns></returns>
missing doc

2020-11-19 16:03 UTC, alexatrhea commented on Modules/StressGenerator/ViewModels/StressGeneratorConfiguration.cs
> +        /// <param name="session"></param>
missing docs all the way

2020-11-19 16:03 UTC, alexatrhea commented on Modules/StressGenerator/Views/Layout.xaml.cs
> +        private void BaseEdit_OnEditValueChanged(object sender, EditValueChangedEventArgs e)
missing docs

2020-11-20 09:58 UTC, lxatrhea approved these changes

2020-11-20 11:16 UTC, cozminvelciu requested changes

2020-11-20 11:16 UTC, cozminvelciu commented on Modules/StressGenerator/Utils/StressGeneratorManager.cs
> +    internal class StressGeneratorManager
This should be renamed to StressGenerator to be in line with Syncer and Migration.

2020-11-20 11:16 UTC, cozminvelciu commented on Modules/StressGenerator/Utils/IterationGenerator.cs
> +                    referencesGenericRdl = true;
return true directly, instead of breaking and returning at the end.

2020-11-20 11:16 UTC, cozminvelciu commented on Modules/StressGenerator/Utils/IterationGenerator.cs
> +            return referencesGenericRdl;
return false at the end and get rid of local variable "referencesGenericRld"

2020-11-20 11:16 UTC, cozminvelciu commented on Modules/StressGenerator/Utils/IterationGenerator.cs
> +                .LastOrDefault(iterationSetup => !iterationSetup.IsDeleted);
Not sure of this, but shouldn't we get the active iteration here, instead of the one with the highest number?

2020-11-20 14:15 UTC, cozminvelciu requested changes

2020-11-20 14:15 UTC, cozminvelciu commented on Modules/StressGenerator/Utils/StressGenerator.cs
> +                }
One extra newline here.

2020-11-20 14:15 UTC, cozminvelciu commented on Modules/StressGenerator/Utils/StressGenerator.cs
> +                    $"Successfully generated ValueSet (Published value: {parameterValue}) for parameter {parameter.ParameterType.Name}({parameter.ParameterType.ShortName}).");
Typo missing whitespace before paranthesis in message.

2020-11-20 14:15 UTC, cozminvelciu commented on Modules/StressGenerator/Utils/StressGenerator.cs
> +                    $"Cannot update ValueSet (Published value: {parameterValue}) for parameter {parameter.ParameterType.Name}({parameter.ParameterType.ShortName}). Exception: {ex.Message}.");
Typo missing whitespace before paranthesis in message.

2020-11-20 15:41 UTC, cozminvelciu commented on Modules/StressGenerator/Utils/StressGenerator.cs
> +                    $"Loading last iteration from EngineeringModel {engineeringModelSetup.ShortName} ...");
Remove whitespace before ellipsis (triple dots).

2020-11-20 15:42 UTC, cozminvelciu commented on Modules/StressGenerator/Utils/StressGenerator.cs
> +                    $"Loading last iteration from EngineeringModel {engineeringModelSetup.ShortName} ...");
Remove whitespace before ellipsis (triple dots).

2020-11-23 09:42 UTC, cozminvelciu approved these changes

2020-12-04 15:25 UTC, adrianchivu commented
@samatrhea If you have something to add to this PR please let me know.
Thank you.

2020-12-07 09:07 UTC, alexatrhea approved these changes
Please merge

2020-12-07 09:16 UTC, merged