POCO Coordinality hotfix and persistent server addresses
RHEAGROUP/CDP4-Server-Administration-Tool pull request #91
Opened 2020-12-09 00:22 UTC by alexatrhea

Persistent server addresses

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-Server-Administration-Tool/pulls) open
- [x] I have verified that I am following the CDP4-SDK [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-Server-Administration-Tool/master/.github/CONTRIBUTING.md)
- [ ] I have provided test coverage for my change (where applicable)

### Description
A mechanism to solve some of the poco coordinality errors. Needs to be verified. No tests provided.

A rudimentary mechanism to save server addresses.

2020-12-09 14:14 UTC, cozminvelciu requested changes

2020-12-09 14:14 UTC, cozminvelciu commented on Modules/Migration/ViewModels/FixCoordinalityErrorsDialogViewModel.cs
> +                                    srdl?.ReferenceSource.Add(referenceSource);
If the SRDL does not exist, we should break the execution earlier (in the previous `switch(topContainer)`), so as to not create a new ReferenceSource and add it to the cache only to realise here that we don't need it.

2020-12-09 14:14 UTC, cozminvelciu commented on Modules/Migration/ViewModels/FixCoordinalityErrorsDialogViewModel.cs
> +
Unneeded extra newline.

2020-12-09 14:14 UTC, cozminvelciu commented on Modules/Migration/ViewModels/FixCoordinalityErrorsDialogViewModel.cs
> +                                    rdl?.ReferenceSource.Add(referenceSource);
This can never be null (see comment on previous `switch(topContainer)`).

2020-12-09 14:14 UTC, cozminvelciu commented on Modules/Migration/ViewModels/FixCoordinalityErrorsDialogViewModel.cs
> +                                    rdl?.ReferenceSource.Add(referenceSource);
Meaning `FirstOrDefault()` can also be replaced with `First()`.

2020-12-09 15:22 UTC, alexatrhea commented
@adrianchivu can you please take over this branch in terms of @cozminvelciu 's requested changes?

2020-12-10 18:02 UTC, alexatrhea commented on Modules/Common/Settings/AppSettingsHandler.cs
> +            Load();
Yes because load syncs and sends the message through MB.

2020-12-10 18:12 UTC, alexatrhea commented on Modules/Migration/ViewModels/FixCoordinalityErrorsDialogViewModel.cs
>          private void ExecuteFixCommand()
I agree, but since the model is the SDK here, for this hotfix the current implementation is fine. We keep the coordinality global fix as the original issue for the SDK to be implemented later.

2020-12-10 18:12 UTC, alexatrhea commented on Modules/Migration/ViewModels/FixCoordinalityErrorsDialogViewModel.cs
> +                if (erroredRow.Error.Contains("ShortName"))
I agree, Feel free to make a "nice to have" issue to refactor this later.

2020-12-10 18:13 UTC, alexatrhea commented on Modules/Migration/ViewModels/FixCoordinalityErrorsDialogViewModel.cs
> +                if (erroredRow.Error.Contains("ShortName"))
I agree. Please make an issue for this later.

2020-12-10 18:14 UTC, alexatrhea commented on Modules/Migration/ViewModels/FixCoordinalityErrorsDialogViewModel.cs
> +                                var srdl = siteDirectory.SiteReferenceDataLibrary.FirstOrDefault();
Not relevant for new commit.

2020-12-10 18:14 UTC, alexatrhea commented on Modules/Migration/ViewModels/FixCoordinalityErrorsDialogViewModel.cs
> +                                if (rdl != null)
not relevant for new commit

2020-12-10 18:14 UTC, alexatrhea commented on Modules/Migration/ViewModels/FixCoordinalityErrorsDialogViewModel.cs
> +                        if (!sourceExists)
not relevant for new commit

2020-12-10 18:14 UTC, alexatrhea commented on Modules/Migration/ViewModels/FixCoordinalityErrorsDialogViewModel.cs
> +                        var sourceExists = referenceSource != null;
not relevant for new commit

2020-12-10 18:14 UTC, alexatrhea commented on Modules/Migration/ViewModels/FixCoordinalityErrorsDialogViewModel.cs
> +                                    srdl?.ReferenceSource.Add(referenceSource);
not relevant for new commit

2020-12-10 18:14 UTC, alexatrhea commented on Modules/Migration/ViewModels/FixCoordinalityErrorsDialogViewModel.cs
> +                                    rdl?.ReferenceSource.Add(referenceSource);
not relevant for new commit

2020-12-10 18:15 UTC, alexatrhea commented on Modules/Migration/ViewModels/FixCoordinalityErrorsDialogViewModel.cs
> +
not relevant for new commit

2020-12-29 11:47 UTC, adrianchivu approved these changes

2020-12-29 13:28 UTC, alexatrhea reviewed
I cant approve as im the author. But looks good to me. Have you tested against a number of models?

2020-12-29 13:55 UTC, adrianchivu commented
> I cant approve as im the author. But looks good to me. Have you tested against a number of models?

XIPE(default seeded)					OK
O_CDF_generic_catalogue 				OK
Admin Tutorial 						Not Works
Calathus								OK
Calathus TUTORIAL						OK
CEW May 19							OK
E_Inspector                                                     OK
E_Inspector.2                                                  OK
LOFT							       OK

Still more test left and different combination also.

2020-12-29 17:16 UTC, alexatrhea commented
@adrianchivu shall i merge?

2021-01-02 14:45 UTC, merged